import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
import warnings

# NLTK for BLEU score
import nltk
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction

# BERTScore
from bert_score import score as bert_score

warnings.filterwarnings("ignore")

def extract_numbers(text):
    """Extracts all standalone numbers from a text."""
    if not isinstance(text, str):
        return set()
    return set(re.findall(r'\b\d+\b', text))

def calculate_hallucination_rate(row, generated_col='Generated_Narrative'):
    """
    Heuristic Hallucination Rate:
    Checks if numbers mentioned in the generated text actually exist in the raw statistical data of that game.
    Returns the percentage of hallucinated numbers in the generated text.
    """
    gen_text = row[generated_col]
    if not isinstance(gen_text, str):
        return 0.0
    
    # Numbers the AI decided to output
    gen_numbers = extract_numbers(gen_text)
    if not gen_numbers:
        return 0.0 # No numbers to hallucinate
        
    # Valid numbers from the actual game stats
    valid_numbers = set()
    for col in row.index:
        if col != generated_col and col != 'Generated_Narrative_Target':
            val = str(row[col])
            # Add standalone numbers from stats
            valid_numbers.update(extract_numbers(val))
            
    # Allow common basketball numbers like 2 (pointers), 3 (pointers) naturally
    valid_numbers.update({'2', '3'})
    
    # Count hallucinations
    hallucinations = [num for num in gen_numbers if num not in valid_numbers]
    return len(hallucinations) / len(gen_numbers)

def plot_radar_chart(bleu, bert, hallucination):
    """Generates a radar chart for the 3 metrics."""
    labels = np.array(['BLEU Score', 'BERTScore', 'Hallucination Rate'])
    
    # Note: Hallucination is usually "lower is better". 
    # To represent it on a chart where "bigger is better", we can plot (1 - Hallucination Rate) 
    # as "Factual Accuracy", but here we will just plot the raw values as requested.
    stats = np.array([bleu, bert, hallucination])
    
    # Close the loop for the radar chart
    angles = np.linspace(0, 2*np.pi, len(labels), endpoint=False)
    stats = np.concatenate((stats, [stats[0]]))
    angles = np.concatenate((angles, [angles[0]]))
    
    fig, ax = plt.subplots(figsize=(6, 6), subplot_kw=dict(polar=True))
    ax.fill(angles, stats, color='blue', alpha=0.25)
    ax.plot(angles, stats, color='blue', linewidth=2)
    
    # Formatting
    ax.set_yticklabels([]) # Hide radial ticks
    ax.set_xticks(angles[:-1])
    ax.set_xticklabels(labels, fontsize=12, fontweight='bold')
    
    # Add text annotations
    for angle, stat, label in zip(angles[:-1], stats[:-1], labels):
        ax.text(angle, stat + 0.05, f"{stat:.3f}", ha='center', va='center', fontsize=11, fontweight='bold')

    plt.title('AI Narrative Generation Metrics', size=16, y=1.1)
    plt.savefig('evaluation_radar_chart.png', bbox_inches='tight')
    print("Radar chart saved to 'evaluation_radar_chart.png'")
    plt.show()

def main():
    # 1. Load the generated dataset
    # Make sure this matches the output generated by PyTorch_Neural_AI.py
    csv_file = 'ai_generated_output.csv'
    
    try:
        df = pd.read_csv(csv_file)
    except FileNotFoundError:
        print(f"Error: {csv_file} not found. Please run your PyTorch script to generate the output first.")
        return

    # Check if we have the necessary columns
    target_col = 'Generated_Narrative_Target'
    gen_col = 'AI_Generated_Narrative' # Adjust if your script named it differently
    
    if target_col not in df.columns or gen_col not in df.columns:
        # Fallback: PyTorch_Neural_AI.py might append columns differently. 
        # Update gen_col to whatever your model's output column is named.
        print(f"Make sure '{target_col}' and '{gen_col}' exist in {csv_file}.")
        return

    # Drop NA rows for evaluation
    df = df.dropna(subset=[target_col, gen_col])

    print(f"Evaluating {len(df)} generated narratives...\n")

    # 2. Calculate BLEU Score
    smooth_func = SmoothingFunction().method1
    bleu_scores = []
    for _, row in df.iterrows():
        reference = [str(row[target_col]).split()]
        candidate = str(row[gen_col]).split()
        bleu = sentence_bleu(reference, candidate, smoothing_function=smooth_func)
        bleu_scores.append(bleu)
    
    avg_bleu = np.mean(bleu_scores)
    print(f"Average BLEU Score: {avg_bleu:.4f}")

    # 3. Calculate BERTScore
    print("Calculating BERTScore... (this may take a moment to download/load the model)")
    cands = df[gen_col].astype(str).tolist()
    refs = df[target_col].astype(str).tolist()
    
    # Uses roberta-large by default in English
    P, R, F1 = bert_score(cands, refs, lang='en', verbose=False)
    avg_bert_f1 = F1.mean().item()
    print(f"Average BERTScore (F1): {avg_bert_f1:.4f}")

    # 4. Calculate Hallucination Rate
    hallucination_rates = df.apply(lambda row: calculate_hallucination_rate(row, gen_col), axis=1)
    avg_hallucination = hallucination_rates.mean()
    print(f"Average Hallucination Rate: {avg_hallucination:.4f} ({avg_hallucination*100:.1f}%)")

    # 5. Plot Radar Chart
    plot_radar_chart(avg_bleu, avg_bert_f1, avg_hallucination)

if __name__ == "__main__":
    main()